### PR TITLE
Fix 3D training with data augmentation

### LINKED ISSUE #1213: TypeError: list indices must be integers or slices, not str
## Issue description

Terminal output (from Wandb): [output.log](https://github.com/ivadomed/ivadomed/files/10219808/output.log)

log: [log.log](https://github.com/ivadomed/ivadomed/files/10219815/log.log)

[version_info.log](https://github.com/ivadomed/ivadomed/files/10219790/version_info.log)

<details><summary>Config file</summary>

```console
{
    "command": "train",
    "gpu_ids": [4],
    "path_output": "seg_lesion_output",
    "model_name": "seg_lesion_model",
    "debugging": true,
    "object_detection_params": {
        "object_detection_path": null,
        "safety_factor": [1.0, 1.0, 1.0]
    },
    "wandb": {
        "wandb_api_key": "9095e2bc9e4ab445d478c9c8a81759ae908be8c6",
        "project_name": "basel-mp2rage-lesion",
        "group_name": "my_group",
        "run_name": "run-1",
        "log_grads_every": 100
    },
    "loader_parameters": {
        "path_data": ["/home/GRAMES.POLYMTL.CA/p101317/data_nvme_p101317/data_seg_mp2rage_20221212_175444/data_processed_lesionseg"],
        "subject_selection": {
            "n": [],
            "metadata": [],
            "value": []
        },
        "target_suffix": [["_lesion-manual", "_lesion-manual2"]],
        "extensions": [],
        "roi_params": {
            "suffix": null,
            "slice_filter_roi": null
        },
        "contrast_params": {
            "training_validation": ["UNIT1"],
            "testing": ["UNIT1"],
            "balance": {}
        },
        "slice_filter_params": {
            "filter_empty_mask": false,
            "filter_empty_input": false
        },
        "slice_axis": "axial",
        "multichannel": false,
        "soft_gt": false
    },
    "split_dataset": {
        "fname_split": null,
        "random_seed": 42,
        "center_test": [],
        "method": "per_patient",
        "balance": null,
        "train_fraction": 0.75,
        "test_fraction": 0.2
    },
    "training_parameters": {
        "batch_size": 4,
        "loss": {
            "name": "DiceLoss"
        },
        "training_time": {
            "num_epochs": 100,
            "early_stopping_patience": 200,
            "early_stopping_epsilon": 0.001
        },
        "scheduler": {
            "initial_lr": 1e-3,
            "lr_scheduler": {
                "name": "CosineAnnealingLR",
                "base_lr": 1e-5,
                "max_lr": 1e-3
            }
        },
        "balance_samples": {
            "applied": false,
            "type": "gt"
        },
        "mixup_alpha": null,
        "transfer_learning": {
            "retrain_model": null,
            "retrain_fraction": 1.0,
            "reset": true
        }
    },
    "default_model": {
        "name": "Unet",
        "dropout_rate": 0.3,
        "bn_momentum": 0.1,
        "depth": 4,
        "is_2d": false,
        "final_activation": "sigmoid"
    },
    "uncertainty": {
        "epistemic": false,
        "aleatoric": false,
        "n_it": 0
    },
    "postprocessing": {"binarize_prediction": {"thr": 0.5}},
    "evaluation_parameters": {},
    "transformation": {
        "Resample": {
            "wspace": 1.0,
            "hspace": 1.0,
            "dspace": 1.0
        },
        "CenterCrop": {
            "size": [32, 64, 128]
        },
        "RandomReverse": {
            "applied_to": ["im", "gt"],
            "dataset_type": ["training"]
        },
        "RandomAffine": {
            "degrees": 10,
            "scale": [0.2, 0.2, 0.2],
            "translate": [0.2, 0.2, 0.2],
            "applied_to": ["im", "gt"],
            "dataset_type": ["training"]
        },
        "ElasticTransform": {
            "alpha_range": [25.0, 35.0],
            "sigma_range": [3.5, 5.5],
            "p": 0.5,
            "applied_to": ["im", "gt"],
            "dataset_type": ["training"]
        },
        "RandomGamma": {
            "log_gamma_range": [-1.5, 1.5],
            "p": 0.5,
            "applied_to": ["im"],
            "dataset_type": ["training"]
        },
        "NumpyToTensor": {},
        "NormalizeInstance": {
            "applied_to": ["im"]
        }
    },
    "Modified3DUNet": {
        "applied": true,
        "length_3D": [32, 64, 128],
        "stride_3D": [32, 64, 128],
        "attention": false,
        "n_filters": 8
    }
}
```

</details>

Possibly related to https://github.com/ivadomed/ivadomed/issues/815

### PR DESCRIPTION
**Pull request by mariehbourget**
#### GitHub

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [x] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [x] I've assigned a reviewer

#### PR contents

- [x] I've consulted [ivadomed's internal developer documentation](https://github.com/ivadomed/ivadomed/wiki) to ensure my contribution is in line with any relevant design decisions
- [x] I've added [relevant tests](https://github.com/ivadomed/ivadomed/wiki/tests) for my contribution
- [x] I've updated the [relevant documentation](https://github.com/ivadomed/ivadomed/wiki/documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

#### In this PR:
This PR fixes #1213 where 3D training would fail when using data augmentation after the merge of PR #1169.
The bug was created by the "sample" (`stack_input` or `stack_gt`) being passed to transforms as _numpy arrays_ instead of _list_.

Because we don't have tests for training in 3D, I added `test_training_3d.py` to testing with 4 tests covering the following scenarios, all including transform (preprocessing and data augmentation):
* 3D 1-class single channel training
* 3D 2-class single channel training
* 3D 1-class multichannel training
* 3D 1-class multi-rater training

I also revised the other changes from PR #1169 and everything else seems correct, but I made some minor corrections on a few comments in `mri3d_subvolume_segmentation_dataset.py` for clarity.

#### To test this PR:

* Run a 3D training with "RandomAffine" in transformations on master branch --> you should have an error that looks like this one:
```
metadata[MetadataKW.ROTATION] = [angle, axes]
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
TypeError: list indices must be integers or slices, not str
```
* Run the same training on this branch --> the training should start as expected.
* See an example of config file and error log in the original issue: https://github.com/ivadomed/ivadomed/issues/1213#issue-1494577149

#### Additional note:
I will open another issue (#1223) regarding the harmonization of `get_item `in `mri2d_segmentation_dataset.py` and `mri3d_subvolume_segmentation_dataset.py`.
Both are doing the same thing but some changes in implementations were done at 2 different times: PR #982 in 2D and PR #1169 in 3D. Because of this, there are some discrepancies in the order of the code or in the use of keywords that makes it hard to compare between 2D and 3D.

## Linked issues
Fixes #1213

### CODE REVIEW

**Review by jcohenadad — APPROVED** [review]
I tried it and 3D training is now working 🎉   Thank you @mariehbourget !!!

**Review by kiristern — APPROVED** [review]
working for me as well now, thank you!

**Comment by mariehbourget** [comment]
Hi @dyt811, I'm having trouble with the CI here.
2 tests from `test_automate_training.py` are not passing for python >=3.7.
I did not do any changes in this PR regarding those tests and other PR from yesterday are OK. Any ideas?

All tests are also passing on my laptop (Ubuntu 20.04, python 3.8)

**Comment by kanishk16** [comment]
Just a heads up: I re-ran the CI for one of the failed jobs, and it's still failing. I guess we could exclude the case of GHA weird behaviour. @mariehbourget Could you share the output for `pip freeze` as I'm afraid it could be related to some package release?

**Comment by mariehbourget** [comment]
> Just a heads up: I re-ran the CI for one of the failed jobs, and it's still failing. I guess we could exclude the case of GHA weird behaviour. ~@mariehbourget Could you share the output for `pip freeze` as I'm afraid it could be related to some package release?~ Let it be... I always forget... I'll check in the successful GHA

Thanks @kanishk16. You're right, it may be due to new dependency releases as some of those tests were OK on Friday (and nothing changed afterwards in the PR).

I'll share the pip freeze of my laptop where the tests are passing on Ubuntu 20.04 python 3.8.

<details><summary>pip freeze</summary>

```console
absl-py==1.3.0
alabaster==0.7.12
apeye==1.2.0
astor==0.8.1
attrs==22.1.0
autodocsumm==0.2.9
Babel==2.10.3
beautifulsoup4==4.11.1
bids-validator==1.9.9
CacheControl==0.12.11
cachetools==5.2.0
certifi==2022.9.24
cfgv==3.3.1
changelog==1.0
-e git+https://github.com/neuropoly/changelog.git@0e1ec93b2a8cde8077751d29db9a3ca3818207c5#egg=changelog_neuropoly
charset-normalizer==2.1.1
click==8.1.3
coloredlogs==15.0.1
consolekit==1.4.1
contourpy==1.0.5
coverage==6.5.0
coveralls==3.3.1
cssutils==2.6.0
csv-diff==1.1
cycler==0.11.0
decopatch==1.4.10
Deprecated==1.2.13
deprecation==2.1.0
deprecation-alias==0.3.1
dict2css==0.3.0
dictdiffer==0.9.0
distlib==0.3.6
docker-pycreds==0.4.0
docopt==0.6.2
docutils==0.16
domdf-python-tools==3.5.0
filelock==3.8.0
flake8==5.0.4
flatbuffers==22.10.26
fonttools==4.38.0
formulaic==0.3.4
gitdb==4.0.9
GitPython==3.1.29
google-auth==2.13.0
google-auth-oauthlib==0.4.6
grpcio==1.50.0
html5lib==1.1
humanfriendly==10.0
humanize==4.4.0
identify==2.5.7
idna==3.4
imageio==2.22.2
imagesize==1.4.1
importlib-metadata==5.0.0
iniconfig==1.1.1
interface-meta==1.3.0
-e git+https://github.com/ivadomed/ivadomed.git@d6385f1c57b7433a57003167c215f2288db3b631#egg=ivadomed
Jinja2==3.1.2
joblib==1.2.0
jsonpointer==2.3
kiwisolver==1.4.4
lockfile==0.12.2
loguru==0.6.0
makefun==1.15.0
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.6.0
mccabe==0.7.0
mistletoe==0.9.0
mpmath==1.2.1
msgpack==1.0.4
natsort==8.2.0
networkx==2.8.7
nibabel==3.2.2
nodeenv==1.7.0
num2words==0.5.12
numpy==1.23.4
oauthlib==3.2.2
onnxruntime==1.13.1
packaging==21.3
pandas==1.4.4
pathtools==0.1.2
Pillow==9.2.0
pkg_resources==0.0.0
platformdirs==2.5.2
pluggy==1.0.0
pre-commit==2.20.0
promise==2.3
protobuf==3.19.6
psutil==5.9.3
py==1.11.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pybids==0.15.5
pycodestyle==2.9.1
pyflakes==2.5.0
Pygments==2.13.0
pypandoc==1.9
pyparsing==2.4.7
pytest==6.2.5
pytest-cases==3.6.13
pytest-console-scripts==1.3.1
pytest-cov==4.0.0
pytest-ordering==0.6
python-dateutil==2.8.2
pytz==2022.5
PyWavelets==1.4.1
PyYAML==6.0
requests==2.28.1
requests-oauthlib==1.3.1
rsa==4.9
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.7
scikit-image==0.19.3
scikit-learn==1.1.3
scipy==1.9.3
seaborn==0.12.1
sentry-sdk==1.10.1
setproctitle==1.3.2
shortuuid==1.0.9
SimpleITK==2.2.0
six==1.16.0
smmap==5.0.0
snowballstemmer==2.2.0
soupsieve==2.3.2.post1
Sphinx==4.3.2
sphinx-autodoc-typehints==1.11.1
sphinx-jsonschema==1.19.1
sphinx-prompt==1.5.0
sphinx-rtd-theme==1.0.0
sphinx-tabs==3.2.0
sphinx-toolbox==2.15.2
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
SQLAlchemy==1.3.24
sympy==1.11.1
tabulate==0.9.0
tensorboard==2.10.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
threadpoolctl==3.1.0
tifffile==2022.10.10
toml==0.10.2
tomli==2.0.1
torch==1.11.0
torchio==0.18.84
torchvision==0.12.0
tqdm==4.64.1
typing_extensions==4.4.0
urllib3==1.26.12
virtualenv==20.16.6
wandb==0.13.4
webencodings==0.5.1
Werkzeug==2.2.2
wrapt==1.14.1
zipp==3.10.0
```

</details>

**Pull request merged**
