### PR TITLE
Reformat configuration_file.rst for docs

### PR DESCRIPTION
**Pull request by ahill187**
## Description

The purpose of this pull request is to refactor the `configuration_file.rst` into a more readable format. I have implemented the Python package [sphinx-jsonschema](https://sphinx-jsonschema.readthedocs.io/en/latest/index.html), which creates structured documentation of json files.

### Example

filmedunet

### CODE REVIEW

**Review by gisellemartel — COMMENTED** [review]
Look's good overall, however I did notice I get a few warnings when building the docs. Not sure how much these are of concern:
```Running Sphinx v3.4.3
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 19 source files that are out of date
updating environment: [new config] 19 added, 0 changed, 0 removed
reading sources... [100%] use_cases                                           
/Users/gisellemartel/ivadomed/ivadomed/main.py:docstring of ivadomed.main.run_command:24: WARNING: Unexpected indentation.
/Users/gisellemartel/ivadomed/ivadomed/main.py:docstring of ivadomed.main.run_command:25: WARNING: Block quote ends without a blank line; unexpected unindent.
/Users/gisellemartel/ivadomed/ivadomed/transforms.py:docstring of ivadomed.transforms.DilateGT:: WARNING: image file not readable: ../../images/dilate-gt.png
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] use_cases                                            
/Users/gisellemartel/ivadomed/docs/source/configuration_file.rst:828: WARNING: Could not lex literal_block as "JSON". Highlighting skipped.
/Users/gisellemartel/ivadomed/docs/source/configuration_file.rst:848: WARNING: Could not lex literal_block as "JSON". Highlighting skipped.```
/Users/gisellemartel/ivadomed/docs/source/configuration_file.rst:886: WARNING: Could not lex literal_block as "JSON". Highlighting skipped.
generating indices... genindex py-modindex done
highlighting module code... [ 71%] ivadomed.scripts.prepare_dataset_vertebral_highlighting module code... [100%] ivadomed.visualize                         
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 6 warnings.

**Comment by ahill187** [comment]
Hmmm...the one about "Could not lex literal block" I think I know what that is, I'll see if I can fix that one. The others were already warnings preceding this pull request.

**Comment by ahill187** [comment]
> /Users/gisellemartel/ivadomed/docs/source/configuration_file.rst:828: WARNING: Could not lex literal_block as "JSON". Highlighting skipped.
> /Users/gisellemartel/ivadomed/docs/source/configuration_file.rst:848: WARNING: Could not lex literal_block as "JSON". Highlighting skipped.```
> /Users/gisellemartel/ivadomed/docs/source/configuration_file.rst:886: WARNING: Could not lex literal_block as "JSON". Highlighting skipped.

This bug is fixed here: https://github.com/ivadomed/ivadomed/pull/650/commits/0535cc3410c8be8bf9e1502feb91990a97b36d8c

**Comment by ahill187** [comment]
> /Users/gisellemartel/ivadomed/ivadomed/main.py:docstring of ivadomed.main.run_command:24: WARNING: Unexpected indentation.
> /Users/gisellemartel/ivadomed/ivadomed/main.py:docstring of ivadomed.main.run_command:25: WARNING: Block quote ends without a blank line; unexpected unindent.

This bug is fixed here: https://github.com/ivadomed/ivadomed/pull/650/commits/8a47e35c1e6ecfe8c567dbac77d1cc5864c852c9

**Comment by ahill187** [comment]
> /Users/gisellemartel/ivadomed/ivadomed/transforms.py:docstring of ivadomed.transforms.DilateGT:: WARNING: image file not readable: ../../images/dilate-gt.png

This bug is due to the `dilate-gt.png` file not existing; I think I'll address that in a different pull request :) Thanks @gisellemartel for catching those!

**Review by gisellemartel — APPROVED** [review]
Look's great! The warning are now no longer there (except the one concerning dilate-gt.png for the future PR)

**Comment by ahill187** [comment]
> Look's great! The warning are now no longer there (except the one concerning dilate-gt.png for the future PR)

Yay! Thanks for catching those, for some reason the JSON ones weren't showing up on my computer...

**Pull request merged**
