### PR TITLE
Restructure the testing folder

### PR DESCRIPTION
**Pull request by ahill187**
In preparation for adding functional tests, I split the `testing` folder into two subfolders, `functional_tests` and `unit_tests`:

```
testing
| -- functional_tests
| -- unit_tests
```

All of the existing tests I placed in the `unit_tests` folder.

### CODE REVIEW

**Review by andreanne-lemay — APPROVED** [review]
Absolutely make sense!

**Comment by andreanne-lemay** [comment]
I can't comment directly on your changes, but I think the tests in `test_scripts` are more functional tests, so I'd put them in the functional folder.

**Comment by ahill187** [comment]
@andreanne-lemay oh good call! I moved it here: https://github.com/ivadomed/ivadomed/pull/577/commits/4118807715c0cc79bc9645512a5fa65b96925b0a

**Comment by jcohenadad** [comment]
@ahill187 could you please add [labels and milestones](https://www.neuro.polymtl.ca/software/contributing#pr_labels) in PRs? Many thanks!

**Pull request merged**
