### PR TITLE
Remove deprecated torch and dev installation instructions

### PR DESCRIPTION
**Pull request by mathieuboudreau**
#### GitHub

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [ ] I've linked relevant issues in the PR body
- [x] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [x] I've assigned a reviewer

#### PR contents

- [x] I've consulted [ivadomed's internal developer documentation](https://github.com/ivadomed/ivadomed/wiki) to ensure my contribution is in line with any relevant design decisions
- [ ] I've added [relevant tests](https://github.com/ivadomed/ivadomed/wiki/tests) for my contribution
- [x] I've updated the [relevant documentation](https://github.com/ivadomed/ivadomed/wiki/documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description

It seems recently you've changed from a manual Torch and Torch vision installation procedure, to including them in your requirements.txt file. However, the documentation in the Readme and the detailed RTD instructions continued to ask the users to install it manually. In particular, for the Mac installtion on RTD, I encountered an error because a file it was telling me to use does not exist anymore:

```
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements_gpu.txt'
```

I've removed three instances I could find in the documentation.

You've also removed the dev requirements file, and so I removed that section in RTD as well.

### CODE REVIEW

**Comment by mathieuboudreau** [comment]
I just found another section that is deprecated but not related to Torch:

https://ivadomed.org/installation.html#developer-only-installation-steps

**Comment by mathieuboudreau** [comment]
I'll remove it and change my title/description to reflect the broader deprecation of instructions

**Comment by kanishk16** [comment]
@mathieuboudreau We're almost on the verge of integrating #1125 that contains the updated installation instructions. Moreover, separate installation instructions for contributors are included in the Contributing Section. A preview to the recent draft of the installation instructions from #1125: https://ivado-medical-imaging--1125.org.readthedocs.build/

**Comment by mathieuboudreau** [comment]
> @mathieuboudreau We're almost on the verge of integrating #1125 that contains the updated installation instructions. Moreover, separate installation instructions for contributors are included in the Contributing Section. A preview to the recent draft of the installation instructions from #1125: https://ivado-medical-imaging--1125.org.readthedocs.build/
> 
> And, any feedback would be appreciated.

Ok gotcha! I was installing IVADOMED for the first time this morning and was encountering a substantial number of roadblocks in the instructions, so just thought I'd pass along the message! Feel free to close this PR if they're all resolved in #1125  !

**Comment by kousu** [comment]
> @kousu @kanishk16 I just saw the updated to-do list in #1125, and it appears the merge of that PR is going to be delayed for a while longer. Might it be possible to merge the PR anyways? Per my description, the current documented installation instructions are broken and have been outdated since May (at least?), and this PR would be a quick fix to help out new users install IVADOMED and bridge the instructions over until the full unification of the documentation is complete.

Just to be clear, that's not a todo list, I've done all those things in https://github.com/ivadomed/ivadomed/pull/1184 and you can compare [your version](https://ivado-medical-imaging--1179.org.readthedocs.build/installation.html] to [mine](https://ivado-medical-imaging--1184.org.readthedocs.build/installation.html).

Personally, I think it's ready to go. I just need a second opinion from someone actually on the ivadomed team.

**Comment by mathieuboudreau** [comment]
>Personally, I think it's ready to go. I just need a second opinion from someone actually on the ivadomed team.

@kousu just checking in to see if #1184 is now closer or farther away from being merged than it was two weeks ago. It seems there's a a few more reviews, but reading the discussions I don't see the light at the end of the tunnel (eg no clear checklist of what needs to be changed for approval). Just reminding that this PR would temporarily resolve the broken installation instructions that are currently live on master, which in my view I think is an urgent issue to be resolved so that new users can install the software by reading the docs.

**Review by kousu — APPROVED** [review]
I re-read your version and you essentially went with what I settled on in #1184: make `pip install ivadomed` prominent.

I like that this version simply has no mention of torch at all, so there's nothing for the bulk of users who will never need to think about torch to get derailed by. If we must have the rare special cases then I'd prefer burying them somewhere out of sight (except when we highlight them by linking someone to them). But that's a discussion we can keep having in #1125.

What do you think @kanishk16?

**Comment by kanishk16** [comment]
I promise to have a closer look at this in an hour or so if that works...

**Comment by kousu** [comment]
That's fine with me, is that fine with you @mathieuboudreau ?

**Comment by mathieuboudreau** [comment]
Yup!

**Review by kanishk16 — APPROVED** [review]
I second with @kousu. As per the reviews so far for #1125 and #1184, we'll be mostly revolving around this, with perhaps a more polished version addressing a few more cases. Since it's a step in the right direction, I wouldn't like to stall this any more.

**Comment by mathieuboudreau** [comment]
Great! Thank you both for considering my PR again! The only slight hiccup you might run into is because both my and your PR are changed the same parts of the documentation, someone might need to manually resolve the conflicts. I could take a look at it if it comes to that! I'll merge this one now then.

**Comment by kousu** [comment]
Don't worry about that. We can handle the conflicts. Cheers!

**Pull request merged**
