### PR TITLE
Change path for images

### PR DESCRIPTION
**Pull request by alexfoias**
Built here: https://ivadomed.org/en/af-transfer_doc_images/

### CODE REVIEW

**Comment by alexfoias** [comment]
@jcohenadad  I removed most of the images. We still have 2 csv files under `/images`: `detailed_results.csv` and `df_compare.csv`.
Should I move them to https://github.com/ivadomed/doc-figures ?

**Comment by jcohenadad** [comment]
> @jcohenadad I removed most of the images. We still have 2 csv files under `/images`: `detailed_results.csv` and `df_compare.csv`.
> Should I move them to https://github.com/ivadomed/doc-figures ?

no-- these are small and non-binary (ie ASCII)

**Comment by alexfoias** [comment]
@lrouhier Could you please review the PR in case I missed any sections?

**Review by andreanne-lemay — APPROVED** [review]
No link seems broken, everything looks good on my end.

There is still one png image in the images/ folder ([ivadomed_logo.png](https://github.com/ivadomed/ivadomed/blob/af/transfer_doc_images/images/ivadomed_logo.png)) and a link to it in [docs/source/conf.py](https://github.com/ivadomed/ivadomed/blob/af/transfer_doc_images/docs/source/conf.py#L207). 
I don't know if there is a reason for this or if it is an oversight. Otherwise, LGTM!

**Comment by alexfoias** [comment]
I tried to change the path in the conf.py for the new repo, but it didn't render correctly (https://github.com/ivadomed/ivadomed/pull/521/commits/335dc46ebbe87ec9ab764d8708e564b93e52fd45)

**Review by jcohenadad — APPROVED** [review]
LGTM 👍  Thank you @alexfoias !

**Comment by charleygros** [comment]
`paper.md` still compiles well, thanks @alexfoias !!

**Pull request merged**
