### PR TITLE
Release version to v2.1.0

### PR DESCRIPTION
**Pull request by andreanne-lemay**
Prepare for 2.1.0 release

### CODE REVIEW

**Comment by jcohenadad** [comment]
it would be cool to introduce the CHANGES.md file before creating this release.

**Comment by jcohenadad** [comment]
i've labeled the PRs with milestones 2.1.0 [here](https://github.com/ivadomed/ivadomed/pulls?q=is%3Apr+is%3Aclosed+milestone%3Av2.1.0).

Can someone please, for each PR, add the appropriate [category label](https://github.com/neuropoly/spinalcordtoolbox/wiki/Label-definition#category)

**Comment by andreanne-lemay** [comment]
> i've labeled the PRs with milestones 2.1.0 [here](https://github.com/ivadomed/ivadomed/pulls?q=is%3Apr+is%3Aclosed+milestone%3Av2.1.0).
> 
> Can someone please, for each PR, add the appropriate [category label](https://github.com/neuropoly/spinalcordtoolbox/wiki/Label-definition#category).
> 
> Once this is done, let me know and i'll generate the CHANGES.md (or you can do it yourself with https://github.com/neuropoly/changelog)

Done in 874a16c :) changelog is very useful and easy to use :tada: !!

**Comment by andreanne-lemay** [comment]
Once I do the release, should I directly copy/paste the content of the CHANGES.md file in the release description?

**Comment by jcohenadad** [comment]
@andreanne-lemay i see that some PRs have two categorie labels: there could be only one. Can you correct please?

**Comment by jcohenadad** [comment]
> Once I do the release, should I directly copy/paste the content of the CHANGES.md file in the release description?

no, you can simply add the following:

[Release notes and Changelog](https://github.com/ivadomed/ivadomed/blob/master/CHANGES.md)

**Pull request merged**
