### PR TITLE
Evenly distribute subjects according to metadata

### PR DESCRIPTION
**Pull request by charleygros**
Atm: we are able to split a given dataset between training / validation and testing sub datasets.
We would like to constraint this split with another variable (eg. clinical state of the patient) so that they are evenly distributed between the 3 sub datasets.

Example: We have severe and mild MS patients. We want to avoid the case were the network is trained on mild patients only and tested on severe cases only. We would like them to be evenly spread. That's what this PR is introducing.

Suggestion:
- add a parameter `balance` in the configuration file, see [ docs/source/configuration_file.rst](https://github.com/ivadomed/ivadomed/pull/423/files).
- use the categorical values of the indicated column to evenly distribute the subjects among training / validation / testing.

Results: see posts below.

TODO if & when the hereabove suggestion got approved:
- Update the config files
- Update the tutorial (with `null`)
- Change testing data config file
- Add specific test for `balance`

### CODE REVIEW

**Comment by charleygros** [comment]
Following tests will be done with this example of `participants.tsv`:
```
participant_id  sex     age     institution_id  disability
sub-01016SACH   -       -       center1 severe
sub-01038PAGU   -       -       center1 severe
sub-01039VITE   -       -       center2 severe
sub-01040VANE   -       -       center2 mild
sub-01042GULE   -       -       center3 severe
sub-07001MOEL   -       -       center4 mild
sub-07003SATH   -       -       center3 severe
sub-07010NABO   -       -       center1 mild
sub-07040DORE   -       -       center4 mild
sub-07043SEME   -       -       center3 mild
sub-08002CHJE   -       -       center1 mild
sub-08027SYBR   -       -       center2 mild
sub-08029IVDI   -       -       center1 severe
sub-08031SEVE   -       -       center4 mild
sub-08037ROGU   -       -       center4 severe
```

**Comment by charleygros** [comment]
## Results on `master`

### per_center:
```
    "split_dataset": {
        "fname_split": null,
        "random_seed": 6,
        "center_test": [],
        "method": "per_center",
        "balance": null,
        "train_fraction": 0.6,
        "test_fraction": 0.2
    }
```
gives:
```
Train: ['sub-08002CHJE', 'sub-07010NABO', 'sub-01039VITE', 'sub-07001MOEL', 'sub-01040VANE', 'sub-08029IVDI', 'sub-08031SEVE']
Valid: ['sub-08027SYBR', 'sub-08037ROGU', 'sub-01038PAGU', 'sub-07040DORE', 'sub-01016SACH']
Test: ['sub-01042GULE', 'sub-07003SATH', 'sub-07043SEME']
```

### per_patient:
```
    "split_dataset": {
        "fname_split": null,
        "random_seed": 6,
        "center_test": [],
        "method": "per_patient",
        "balance": null,
        "train_fraction": 0.6,
        "test_fraction": 0.2
    }
```
gives:
```
Train: ['sub-07001MOEL', 'sub-08029IVDI', 'sub-01038PAGU', 'sub-01016SACH', 'sub-08037ROGU', 'sub-01042GULE', 'sub-01040VANE', 'sub-07043SEME', 'sub-08002CHJE']
Valid: ['sub-01039VITE', 'sub-07040DORE', 'sub-08027SYBR']
Test: ['sub-07010NABO', 'sub-08031SEVE', 'sub-07003SATH']
```

**Comment by charleygros** [comment]
## Can we reproduce `master` results?

### per_center:
```
    "split_dataset": {
        "fname_split": null,
        "random_seed": 6,
        "center_test": [],
        "method": "per_center",
        "balance": null,
        "train_fraction": 0.6,
        "test_fraction": 0.2
    }
```
gives:
```
Train: ['sub-08002CHJE', 'sub-07010NABO', 'sub-01039VITE', 'sub-07001MOEL', 'sub-01040VANE', 'sub-08029IVDI', 'sub-08031SEVE']
Valid: ['sub-08027SYBR', 'sub-08037ROGU', 'sub-01038PAGU', 'sub-07040DORE', 'sub-01016SACH']
Test: ['sub-01042GULE', 'sub-07003SATH', 'sub-07043SEME']
```

### per_patient:
```
    "split_dataset": {
        "fname_split": null,
        "random_seed": 6,
        "center_test": [],
        "method": "per_patient",
        "balance": null,
        "train_fraction": 0.6,
        "test_fraction": 0.2
    }
```
gives:
```
Train: ['sub-07001MOEL', 'sub-08029IVDI', 'sub-01038PAGU', 'sub-01016SACH', 'sub-08037ROGU', 'sub-01042GULE', 'sub-01040VANE', 'sub-07043SEME', 'sub-08002CHJE']
Valid: ['sub-01039VITE', 'sub-07040DORE', 'sub-08027SYBR']
Test: ['sub-07010NABO', 'sub-08031SEVE', 'sub-07003SATH']
```

## Answer:
Yes.

**Comment by charleygros** [comment]
## Does the implementation fit the PR purpose?

### Seed 1:
```
    "split_dataset": {
        "fname_split": null,
        "random_seed": 6,
        "center_test": [],
        "method": "per_patient",
        "balance": "disability",
        "train_fraction": 0.6,
        "test_fraction": 0.2
    }
```
gives:
```
Train: ['sub-01016SACH', 'sub-01042GULE', 'sub-01038PAGU', 'sub-01039VITE', 'sub-07043SEME', 'sub-07040DORE', 'sub-07001MOEL', 'sub-07010NABO']
Valid: ['sub-07003SATH', 'sub-08029IVDI', 'sub-01040VANE', 'sub-08031SEVE']
Test: ['sub-08037ROGU', 'sub-08002CHJE', 'sub-08027SYBR']
```
Mild / Severe count: Train (4/4), Valid (2/2), Test (2/1)

### Seed 2:
```
    "split_dataset": {
        "fname_split": null,
        "random_seed": 6666,
        "center_test": [],
        "method": "per_patient",
        "balance": "disability",
        "train_fraction": 0.6,
        "test_fraction": 0.2
    }
```
gives:
```
Train: ['sub-01039VITE', 'sub-08029IVDI', 'sub-08037ROGU', 'sub-01038PAGU', 'sub-07010NABO', 'sub-08027SYBR', 'sub-08031SEVE', 'sub-07001MOEL']
Valid: ['sub-01016SACH', 'sub-01042GULE', 'sub-01040VANE', 'sub-07043SEME']
Test: ['sub-07003SATH', 'sub-08002CHJE', 'sub-07040DORE']
```
Mild / Severe count: Train (4/4), Valid (2/2), Test (2/1)

### Seed 3:
```
    "split_dataset": {
        "fname_split": null,
        "random_seed": 1234,
        "center_test": [],
        "method": "per_patient",
        "balance": "disability",
        "train_fraction": 0.6,
        "test_fraction": 0.2
    }
```
gives:
```
Train: ['sub-01016SACH', 'sub-07003SATH', 'sub-08029IVDI', 'sub-01042GULE', 'sub-07043SEME', 'sub-08002CHJE', 'sub-07040DORE', 'sub-08031SEVE']
Valid: ['sub-01039VITE', 'sub-01038PAGU', 'sub-07010NABO', 'sub-07001MOEL']
Test: ['sub-08037ROGU', 'sub-08027SYBR', 'sub-01040VANE']
```
Mild / Severe count: Train (4/4), Valid (2/2), Test (2/1)

## Answer:
I think so..

**Comment by olix86** [comment]
The example is on MS brain dataset right? Sounds like a really useful feature for small dataset like this one 😃

**Comment by andreanne-lemay** [comment]
Very well done! I started the to do list:
- I added a split dataset test to make sure all are split are done correctly.
- I added a condition (91de263) so we don't have to change config files, the tutorial or the config in the tests.

If you agree with these changes, it is good to merge for me :)!

**Comment by charleygros** [comment]
Thanks for your help @andreanne-lemay !

>      so we don't have to change config files, the tutorial or the config in the tests.

Great for making it optional! I was thinking of editing the cnfig files anyway just so that people are aware it exists!

**Review by olix86 — APPROVED** [review]

**Pull request merged**
