### PR TITLE
Input-level dropout feature

### PR DESCRIPTION
**Pull request by andreanne-lemay**
## Description
This PR implements the input-level dropout presented in https://www.nature.com/articles/s41746-021-00398-4. The purpose of this feature is to train models robust to missing modalities. When the option is enabled, 0 to all channels - 1 are randomly chosen to be set to zeros simulating missing modalities. If a channel is already empty due to an actual missing modality, it will be considered by the function as a dropped modality.

To apply the input-level dropout, the following optional parameter can be set to `True`:

```
"loader_parameters": {
    "is_input_dropout": true
}
```

## Linked issues
This method is a simpler alternative to HeMIS which presented poor results #686. It can also a good training strategy for the Karolinska model which has partial missing modalities (see [issue](https://github.com/ivadomed/pipeline-ms-lesion/issues/3) )

## PR content
- [x] Addition of `dropout_input` function
- [x] PEP8 correction in the `main.py` file 
- [x] Update RDT
- [x] Add unit test

## Design questions
Do we want to allow more than one modality to be set to zero?
Do we want an option to decide which modality we want to drop (e.g., always train with T2w or T1w, but always keep T2star)?
Do we want to allow input dropout at test time (currently it's impossible)?

Update: These questions have been addressed further in this PR.

### CODE REVIEW

**Comment by charleygros** [comment]
First and foremost, this is 1,000 cool.

> ## Design questions
> 
> Do we want to allow more than one modality to be set to zero?

In real life datasets, that's what we experiment... so I would say yes! (ofc: make sure at least one is available).

> Do we want an option to decide which modality we want to drop (e.g., always train with T2w or T1w, but always keep T2star)?

Yes! And I was thinking of a suggestion that we could couple with your question: What about adding a parameter that controls the frequency of this dropping? AND this dropping could be modality dependent. For instance, having in the config file: `[0.5, 0.7, 1]` for "T2w or T1w can drop but always keep T2star".

> Do we want to allow input dropout at test time (currently it's impossible)?

That would be good to validate (eg with SpineGeneric) this method before running it on our real life dataset, so I would say yes!

Thinking out loud: Let's say you have a dataset with 3 images for each subjects, same size, same resolution, co registered. But, as they have different coverage along (IS), some sections (eg top of T2star) are filled with zeros --> so basically we will have the same behaviour that you are forcing here while having `is_input_dropout: false` and `"filter_empty_input": false`. So for this dataset we will not use this feature per say (except if we want to do some transfer learning etc). But this paper (and this implementation) kinda validates that this approach is promising for our user case.

**Comment by charleygros** [comment]
Thinking out loud: Let's say you have a dataset with 3 images for each subjects, same size, same resolution, co registered. But, as they have different coverage along (IS), some sections (eg top of T2star) are filled with zeros --> so basically we will have the same behaviour that you are forcing here while having is_input_dropout: false and "filter_empty_input": false. So for this dataset we will not use this feature per say (except if we want to do some transfer learning etc). But this paper (and this implementation) kinda validates that this approach is promising for our user case.

**Comment by charleygros** [comment]
Again just thinking, as the intensity normalisation is done per channel (with the @ thingy) we will not have issues with dropped channels. All goodie.

**Comment by andreanne-lemay** [comment]
> > ## Design questions
> > Do we want to allow more than one modality to be set to zero?
> 
> In real life datasets, that's what we experiment... so I would say yes! (ofc: make sure at least one is available).

Great, so I updated the code to fit this behavior (40f1fc1). From 0 to all channels - 1 will be dropped.



> > Do we want to allow input dropout at test time (currently it's impossible)?
> 
> That would be good to validate (eg with SpineGeneric) this method before running it on our real life dataset, so I would say yes!

Goop point! I enabled the option to dropout inputs during testing but I added a warning to inform the user if the option is on during test time (70d984d). 




> > Do we want an option to decide which modality we want to drop (e.g., always train with T2w or T1w, but always keep T2star)?
> 
> Yes! And I was thinking of a suggestion that we could couple with your question: What about adding a parameter that controls the frequency of this dropping? AND this dropping could be modality dependent. For instance, having in the config file: `[0.5, 0.7, 1]` for "T2w or T1w can drop but always keep T2star".

I didn't implement this option yet, but it would be very interesting! I think the first step would be to test the current version, and I believe the model will benefit to be trained when all modalities can be dropped since it teaches the model to predict in harder conditions.

**Review by charleygros — APPROVED** [review]
Looks ready to be merged :-)

I opened an issue, #730, re the dropping parameter, so that we remember about it.

**Pull request merged**
