### PR TITLE
Remove data dependencies from `if` statements in the `Decoder()` forward pass

### LINKED ISSUE #749: `Type 'tensor(bool)'` error when loading .ONNX representation of `seg_exvivo_gm-wm_t2`
> **Note:** Creating this issue using @charleygros's comment on https://github.com/neuropoly/spinalcordtoolbox/pull/3321#issuecomment-810725960

The error occurs when loading the .ONNX model file using `onnxruntime.InferenceSession(model_path)`: 

```
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_deepseg.py", line 245, in <module>
    main(sys.argv[1:])
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_deepseg.py", line 207, in main
    nii_lst, target_lst = imed_inference.segment_volume(path_model, input_filenames, options=options)
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/ivadomed/inference.py", line 264, in segment_volume
    preds = model(img) if fname_model.endswith('.pt') else onnx_inference(fname_model, img)
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/ivadomed/inference.py", line 377, in onnx_inference
    ort_session = onnxruntime.InferenceSession(model_path)
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 158, in __init__
    self._load_model(providers or [])
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 177, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Type Error: Type 'tensor(bool)' of input parameter (281) of operator (ScatterND) in node (ScatterND_160) is invalid.
```

This looks to be the same error message as https://github.com/microsoft/onnxruntime/issues/1807. That link suggests that the problem is due to indexing using a boolean tensor, which doesn't comply with the ONNX spec. If this is indeed the cause, then https://github.com/microsoft/onnxruntime/issues/1807#issuecomment-530508235 / https://github.com/onnx/onnx/issues/2302 suggests to use [`torch.where`](https://pytorch.org/docs/stable/generated/torch.where.html) to turn the boolean tensor into absolute indices. 

(I haven't looked at the model definition, though, so I can't confirm this yet.)

### PR DESCRIPTION
**Pull request by joshuacwnewton**
#### GitHub

- [X] I've given this PR a concise, self-descriptive, and meaningful title
- [X] I've linked relevant issues in the PR body
- [X] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [X] I've assigned a reviewer

#### PR contents

- [X] I've consulted [ivadomed's internal developer documentation](https://github.com/ivadomed/ivadomed/wiki) to ensure my contribution is in line with any relevant design decisions
- [ ] I've added [relevant tests](https://github.com/ivadomed/ivadomed/wiki/tests) for my contribution
- [ ] I've updated the [relevant documentation](https://github.com/ivadomed/ivadomed/wiki/documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description

`if` statements that are dependent on data cause the following warning when trying to trace the model:

```
TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
```

I believe this is responsible for the error encountered when loading a converted `.ONNX` model:

```
INVALID_GRAPH : This is an invalid model. Type Error: Type 'tensor(bool)' of input parameter (281) of operator (ScatterND) in node (ScatterND_160) is invalid.
```

So, by removing the data dependency, we should (hopefully!) be able to export `.pt` U-Net models to the `.ONNX` representation. 

(I haven't tested these changes yet, though (e.g. by retraining a model and trying to convert it), so CC: @charleygros regarding the exvivo model.)

## Linked issues

Tangentially related to #749.

### CODE REVIEW

**Review by andreanne-lemay — APPROVED** [review]
Looks great! Thanks for investigating and taking care of this :100:

**Review by charleygros — APPROVED** [review]
Fingers crossed!!
Thanks @joshuacwnewton

**Review by jcohenadad — CHANGES_REQUESTED** [review]
as discussed in meeting, @charleygros will test the ONNX model before merging this PR to make it solves the problem

**Comment by charleygros** [comment]
Follow-up: model retrained using this PR.
Next step: check whether it fixes bug when onnx model is used in SCT env. TODO charley

**Comment by charleygros** [comment]
@joshuacwnewton: I did the following:
- Trained a onnx model using this current branch
- Used `sct_deepseg` from SCT master (so with ivadomed_master installed) with the above onnx model
- Got the following error:
```
    main(sys.argv[1:])
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/spinalcordtoolbox/scripts/sct_deepseg.py", line 207, in main
    nii_lst, target_lst = imed_inference.segment_volume(path_model, input_filenames, options=options)
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/ivadomed/inference.py", line 264, in segment_volume
    preds = model(img) if fname_model.endswith('.pt') else onnx_inference(fname_model, img)
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/ivadomed/inference.py", line 377, in onnx_inference
    ort_session = onnxruntime.InferenceSession(model_path)
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 158, in __init__
    self._load_model(providers or [])
  File "/home/GRAMES.POLYMTL.CA/chgroc/spinalcordtoolbox/python/envs/venv_sct/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 177, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Type Error: Type 'tensor(bool)' of input parameter (278) of operator (ScatterND) in node (ScatterND_157) is invalid.
```

If you want to try: I've just pushed this onnx model on the model repo' --> [here](https://github.com/ivadomed/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg/blob/main/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg.onnx).

@joshuacwnewton : Do you think I should try with this current ivadomed branch installed in SCT? Does it matter? I thought it should not but..

**Comment by joshuacwnewton** [comment]
Thank you for testing this! Just to clarify this step:

> * Trained a onnx model using this current branch

Did you train a `.pt` model, then convert it to `.onnx` using `convert_to_onnx.py`? And, did you see the same warnings mentioned in https://github.com/ivadomed/ivadomed/issues/749#issuecomment-812574057?

**Comment by charleygros** [comment]
> Did you train a `.pt` model, then convert it to `.onnx` using `convert_to_onnx.py`? And, did you see the same warnings mentioned in [#749 (comment)](https://github.com/ivadomed/ivadomed/issues/749#issuecomment-812574057)?

I have not used `convert_to_onnx.py`: the model was saved with the onnx format at the [end of the training](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/training.py#L326).

I'm now trying the `convert_to_onnx.py` on the `.pt` model. BRB

**Comment by charleygros** [comment]
> I'm now trying the `convert_to_onnx.py` on the `.pt` model. BRB

No warning when using this command!
Now trying this resulting onnx model with SCT. BRB_bis

**Comment by charleygros** [comment]
>  Now trying this resulting onnx model with SCT. BRB_bis

Same error pops up :/

**Comment by joshuacwnewton** [comment]
> No warning when using this command!

That's good to hear, but it seems like this means that the warnings were unrelated to the ONNX issue. My apologies -- this might require further investigation, then. :sweat_smile:

**Comment by charleygros** [comment]
@joshuacwnewton It may be worth merging this PR as it fixes the warning thing while no alteration of model behaviour. What do ya reckon?

**Comment by joshuacwnewton** [comment]
Good point. I've unlinked the issue so it won't get auto-closed. :slightly_smiling_face:

**Comment by joshuacwnewton** [comment]
Also, out of curiosity, could you share the code you used to train the model? I'd love to learn how to use ivadomed, so I can test out potential solutions without having to nag you each time. :sweat_smile:

**Comment by charleygros** [comment]
> Good point. I've unlinked the issue so it won't get auto-closed. 🙂

Great! just waiting for @jcohenadad approval

> Also, out of curiosity, could you share the code you are using to train the model @charleygros?

For instance for this particular task / dataset: you could simply run this command from `rosenberg` (or similar):
```
ivadomed -c config.json
```

With this [file ](https://github.com/ivadomed/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg/blob/main/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg.json) as `config.json`.
Plenty of parameters, but to reproduce the present experiment, the only thing to be careful is `path_data`, which is the path towards the training dataset. You should not have to worry about the other params too much.

**Comment by jcohenadad** [comment]
i'm sorry i cannot review this PR in a meaningful way (i don't understand the lines of code that are changed and i do not have the time to test before/after the change to evaluate the effective change that this PR brings)

**Comment by charleygros** [comment]
> i'm sorry i cannot review this PR in a meaningful way (i don't understand the lines of code that are changed and i do not have the time to test before/after the change to evaluate the effective change that this PR brings)

Oh sorry, I did not mean to ask you to review it / evaluate the effective change --> I've reviewed it and I think we should merge it. But blocked by GH because you "requested changes" earlier --> I don't know how to overpass this without your intervention, sorry about that.

**Review by jcohenadad — APPROVED** [review]

**Pull request merged**
