### PR TITLE
Fix import of int_classes from torch._six in torch version 1.9+

### PR DESCRIPTION
**Pull request by etetteh**
Although the current ivadomed implementation is built on torch version 1.8, newer versions of torch no longer support importing int_classes from torch._six, and we need to remedy this in a future update of ivadomed when upgrading the underlying version of torch.

This PR proposes the fix for the said issue.

### CODE REVIEW

**Comment by konantian** [comment]
Maybe we could upgrade `torch` to 1.10 in `requirements.txt` as well.

**Comment by etetteh** [comment]
Yes, that would be my best suggestion

**Comment by konantian** [comment]
This PR also resolved issue #1035

**Comment by dyt811** [comment]
> Maybe we could upgrade `torch` to 1.10 in `requirements.txt` as well.

I agree we should do more tastings as well and eventually move to 1.10 in the near future.

**Review by dyt811 — APPROVED** [review]
So far, this is one of the fixes that have been widely documented across the web to support forward compatibility. 

Please ensure in future PRs, follow the recommended format as indicated in the template to facilitate review and documentation purposes (especially when eventually release notes will link back to this PR for explanation and context).

**Pull request merged**
