### PR TITLE
Installation instruction steps explicity recommended for MacOS but not Linux

### LINKED ISSUE #839: Installation instruction steps explicity recommended for MacOS but not Linux
The installation instructions on Ivadomed (https://ivadomed.org/en/latest/installation.html) mention:

> Currently, we only support MacOS and Linux operating systems. Windows users have the possibility to install and use ivadomed via Windows Subsystem for Linux (WSL).For MacOs users, we strongly recommend to follow the bellow steps before the installation.

As a new user this was a little confusing because it gave me an impression that detailed Linux instructions are elsewere (or after MacOS). Is there a particular reason to mention this strong recommendation for MacOS. Are there alternatives of linux?

**Suggestion:**
Since the first line already mentions `we only support MacOS and Linux operating systems`, we can do **one** of the folllowing:

1. Remove `For MacOs users, we strongly recommend to follow the bellow steps before the installation.`  OR
2.  Add an additional line saying something for linux to avoid confusion.

### PR DESCRIPTION
**Pull request by copperwiring**
#### GitHub

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [x] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [x] I've assigned a reviewer

#### PR contents

- [x] I've consulted [ivadomed's internal developer documentation](https://github.com/ivadomed/ivadomed/wiki) to ensure my contribution is in line with any relevant design decisions
- [ ] I've added [relevant tests](https://github.com/ivadomed/ivadomed/wiki/tests) for my contribution
- [x] I've updated the [relevant documentation](https://github.com/ivadomed/ivadomed/wiki/documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description

The installation instructions on Ivadomed (https://ivadomed.org/en/latest/installation.html) mention:

> Currently, we only support MacOS and Linux operating systems. Windows users have the possibility to install and use ivadomed via Windows Subsystem for Linux (WSL).For MacOs users, we strongly recommend to follow the bellow steps before the installation.

As a new user this is a little confusing because it gave me an impression that detailed Linux instructions are elsewhere. This PR fixes the documentation to make the installation steps clear (i.e. the mentioned step is recommended for MacOS users and option for Linux)

## Linked issues

Fixes #839

### CODE REVIEW

**Review by konantian — CHANGES_REQUESTED** [review]
Since there are many macOS users who are using zsh instead of bash, you might need to mention zshrc here as well.

**Comment by copperwiring** [comment]
> Since there are many macOS users who are using zsh instead of bash, you might need to mention zshrc here as well.

@konantian Looks like it's already there:

image

Do we need to change anything here?

**Comment by konantian** [comment]
> > Since there are many macOS users who are using zsh instead of bash, you might need to mention zshrc here as well.
> 
> @konantian Looks like it's already there:
> 
> image
> 
> Do we need to change anything here?

Everything looks good, no changes are needed!

**Comment by copperwiring** [comment]
> > > Since there are many macOS users who are using zsh instead of bash, you might need to mention zshrc here as well.
> > 
> > 
> > @konantian Looks like it's already there:
> > image
> > Do we need to change anything here?
> 
> Everything looks good, no changes are needed!

Thanks, @konantian . If you can approve it, I can merge and close this issue.

**Review by konantian — APPROVED** [review]

**Pull request merged**
