### PR TITLE
Update changelog and version.txt for v2.9.9

### PR DESCRIPTION
**Pull request by joshuacwnewton**
## Description

I'm hoping to release ivadomed v2.9.9 to unlock compatibility with `torch>=2.0.0` in SCT, which will allow us to integrate MONAI/nnUnet-based projects into SCT.

Creating a new ivadomed release requires updating the changelog, hence this PR. I've followed the steps on the [Releases](https://github.com/ivadomed/ivadomed/wiki/Releases) page of the ivadomed Wiki (labeling PRs, running `changelog`).

### CODE REVIEW

**Comment by joshuacwnewton** [comment]
It seems the RTD documentation build failed while trying to download the PyTorch wheel:

image

I assume this is just an anomaly? But, I can't restart the RTD build as my account doesn't have privileges for ivadomed.

**Comment by mathieuboudreau** [comment]
> It seems the RTD documentation build failed while trying to download the PyTorch wheel:
> 
> image
> 
> I assume this is just an anomaly? But, I can't restart the RTD build as my account doesn't have privileges for ivadomed.

If the RTD uses an environment file with conda-forge, this caused a memory for us lately in AxonDeepSeg: https://github.com/axondeepseg/axondeepseg/pull/777.

Also, we use a separate RTD environment file that doesn't install the entire software to help resolve ease the memory load on RTD: https://github.com/axondeepseg/axondeepseg/blob/master/docs/environment.yml

**Comment by kanishk16** [comment]
> It seems the RTD documentation build failed while trying to download the PyTorch wheel:
> 
> image
> 
> I assume this is just an anomaly? But, I can't restart the RTD build as my account doesn't have privileges for ivadomed.

Yup, neither do I have, but perhaps you could trigger the RTD build by adding a newline to the `CHANGES.md`. In case this doesn't work, we'd go as @mathieuboudreau suggested.

**Review by kanishk16 — APPROVED** [review]
LGTM 🚀

**Comment by joshuacwnewton** [comment]
> Yup, neither do I have, but perhaps you could trigger the RTD build by adding a newline to the `CHANGES.md`. If this doesn't work, we'd go as @mathieuboudreau suggested, or we might merge as it is since we're pretty confident about the changes.

I think I'm OK to merge, personally, given the [recent passes](https://readthedocs.org/projects/ivado-medical-imaging/builds/)? Plus the fact that this is just a changelog update.

**Comment by mathieuboudreau** [comment]
Thank you both!

**Pull request merged**
