### PR TITLE
Version pin sphinx.

### PR DESCRIPTION
**Pull request by kousu**

### CODE REVIEW

**Comment by kousu** [comment]
I got rid of the `requirements: requirements.txt` line because it's redundant, and my impression is requirements.txt files are slowly on their way to deprecation; we already load it in setup.py anyway, and `method: pip` implies doing `pip install .` which means using setup.py.

**Comment by kousu** [comment]
Please double-check that the instructions I wrote work for you!

**Comment by kousu** [comment]
Sorry this isn't ready yet it's still buggy.

**Review by lrouhier — APPROVED** [review]
looks good.

**Pull request merged**
