### PR TITLE
Add Attention module to 2D Unet

### PR DESCRIPTION
**Pull request by AshkanTaghipour**
Due to a better understanding of the network, I wrote the ENCODE, DECODER, and the Unet class from scratch. The network architecture is exactly the same as the original paper except for the padding.
In the DECODER section, I used the transposed convolution which I think in IVADOMED architecture the interpolation has been used.

### CODE REVIEW

**Comment by charleygros** [comment]
Many thanks @AshkanTaghipour for your contribution. That's really appreciated! It looks like your work is directly related to this issue #443.

The next steps would be to:
- move the Attention module you've implemented from your Jupyter Notebook to the `ivadomed` code base, in `ivadomed/models.py`
- make it compatible with our `Unet` class, see [here](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/models.py#L460).
- limit duplication with existing Attention module, see [here](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/models.py#L1131) --> Ideally we would like to have a module compatible with both 2D and 3D Unet architectures.

Please let me know your thoughts and if you need help with any of these.

Fixes #443.

**Comment by jcohenadad** [comment]
Thank you @AshkanTaghipour ! Adding a unit tests to your code would also be important.

**Comment by AshkanTaghipour** [comment]
@jcohenadad @charleygros Thanks for your valuable feedback, I read the attention Gate paper and will do according to your suggestions.

**Comment by AshkanTaghipour** [comment]
@charleygros Dear Charley, is there any specific reason that the number of filters has not been doubled in the bottom layer of the ENCODER class?
I think that in the original U-net architecture, the number of filters is doubled in the bottom layer.
((https://github.com/ivadomed/ivadomed/blob/2d35c6287034d3d342066b97e5e949cf8a3598f8/ivadomed/models.py#L334))

**Comment by AshkanTaghipour** [comment]
The 2D attention U-net implemented in the following link:
https://github.com/AshkanTaghipour/Attention_2D_Unet/blob/main/2D_attention_Unet.ipynb

**Comment by charleygros** [comment]
> @charleygros Dear Charley, is there any specific reason that the number of filters has not been doubled in the bottom layer of the ENCODER class?
> I think that in the original U-net architecture, the number of filters is doubled in the bottom layer.

`n_filters` is doubled [here](https://github.com/ivadomed/ivadomed/blob/2d35c6287034d3d342066b97e5e949cf8a3598f8/ivadomed/models.py#L331). Please let me know if I misunderstood your question. Cheers.

**Comment by charleygros** [comment]
> The 2D attention U-net implemented in the following link:
> https://github.com/AshkanTaghipour/Attention_2D_Unet/blob/main/2D_attention_Unet.ipynb

It looks good! Would you be interested in integrating your implementation into `ivadomed` code base? That would be really appreciated!

**Comment by AshkanTaghipour** [comment]
> > @charleygros Dear Charley, is there any specific reason that the number of filters has not been doubled in the bottom layer of the ENCODER class?
> > I think that in the original U-net architecture, the number of filters is doubled in the bottom layer.
> 
> `n_filters` is doubled [here](https://github.com/ivadomed/ivadomed/blob/2d35c6287034d3d342066b97e5e949cf8a3598f8/ivadomed/models.py#L331). Please let me know if I misunderstood your question. Cheers.

I think that in the following line (the bottom layer) the n_filters should be doubled.
https://github.com/ivadomed/ivadomed/blob/2d35c6287034d3d342066b97e5e949cf8a3598f8/ivadomed/models.py#L334
which means that the above line should be written in the following manner:
self.conv_bottom = DownConv(n_filters, n_filters*2, drop_rate, bn_momentum, is_2d)
because the number of channels in the DownConv of the bottom layer doubled in the Unet architecture.

**Comment by AshkanTaghipour** [comment]
> > The 2D attention U-net implemented in the following link:
> > https://github.com/AshkanTaghipour/Attention_2D_Unet/blob/main/2D_attention_Unet.ipynb
> 
> It looks good! Would you be interested in integrating your implementation into `ivadomed` code base? That would be really appreciated!
> 
> EDIT: Looks like that s what you are doing here. #552 ! I will have a look at it now. Should we close this PR then?

Thank you very much, I added unit tests for evaluation of models, but I have some trouble and I think the unit tests act based on the previous Ivadomed code base, not my Ivadomed revision. 
would you mind helping me with this issue?
the revised unit test section is [here](https://github.com/AshkanTaghipour/ivadomed/edit/master/testing/test_model.py)

**Comment by charleygros** [comment]
> I have some trouble and I think the unit tests act based on the previous Ivadomed code base, not my Ivadomed revision.
> would you mind helping me with this issue?
> the revised unit test section is [here](https://github.com/AshkanTaghipour/ivadomed/edit/master/testing/test_model.py)

I am happy to help, of course :-) But it is very difficult to review if not integrated in the ivadomed code base using the GH tools (Pull Request etc.).
I would suggest to work on the ivadomed repo, as you started in #555, using the last version of `master` / `main`.

**Comment by AshkanTaghipour** [comment]
> > I have some trouble and I think the unit tests act based on the previous Ivadomed code base, not my Ivadomed revision.
> > would you mind helping me with this issue?
> > the revised unit test section is [here](https://github.com/AshkanTaghipour/ivadomed/edit/master/testing/test_model.py)
> 
> I am happy to help, of course :-) But it is very difficult to review if not integrated in the ivadomed code base using the GH tools (Pull Request etc.).
> I would suggest to work on the ivadomed repo, as you started in #555, using the last version of `master` / `main`.

So, in the last version of 'master'/ 'main' the revised attention 2D module added to the models.py?

**Comment by charleygros** [comment]
@AshkanTaghipour : It would be useful to have the new code and the related new tests in the same PR. So essentially: to move the tests from #555 to #552 --> so that you will be able to test your new code before merging this PR. What do you think?

**Comment by AshkanTaghipour** [comment]
> @AshkanTaghipour : It would be useful to have the new code and the related new tests in the same PR. So essentially: to move the tests from #555 to #552 --> so that you will be able to test your new code before merging this PR. What do you think?

fantastic :-) and how can I move from [#555 ](https://github.com/ivadomed/ivadomed/pull/555) to [#552 ](https://github.com/ivadomed/ivadomed/pull/552) ?

**Comment by jcohenadad** [comment]
> > @AshkanTaghipour : It would be useful to have the new code and the related new tests in the same PR. So essentially: to move the tests from #555 to #552 --> so that you will be able to test your new code before merging this PR. What do you think?
> 
> fantastic :-) and how can I move from [#555 ](https://github.com/ivadomed/ivadomed/pull/555) to [#552 ](https://github.com/ivadomed/ivadomed/pull/552) ?

i think you can figure that one 😉

**Comment by AshkanTaghipour** [comment]
> > > @AshkanTaghipour : It would be useful to have the new code and the related new tests in the same PR. So essentially: to move the tests from #555 to #552 --> so that you will be able to test your new code before merging this PR. What do you think?
> > 
> > 
> > fantastic :-) and how can I move from [#555 ](https://github.com/ivadomed/ivadomed/pull/555) to [#552 ](https://github.com/ivadomed/ivadomed/pull/552) ?
> 
> i think you can figure that one 😉

Wonderful, if you let me do it tomorrow, it is 3 in the morning here and tomorrow will be a nice day to learn new things :-)))

**Comment by AshkanTaghipour** [comment]
all modifications in `models.py` and adding test units in `test_model.py` and related discussions can be followed in [#552](https://github.com/ivadomed/ivadomed/pull/552)

**Pull request closed without merging**
