### PR TITLE
Redirect to DokuWiki/GitHub from the contributing guidelines

### LINKED ISSUE #373: Update contribution.rst with information about labels
this could be added to ivadomed's contribution guideline: https://github.com/neuropoly/spinalcordtoolbox/blob/master/CONTRIBUTING.rst#pr-labels

### PR DESCRIPTION
**Pull request by joshuacwnewton**
### Related PRs/Issues

Fixes #373. (See @jcohenadad's https://github.com/ivadomed/ivadomed/issues/373#issuecomment-724201969)

### Description

* I've added sections to the centralized NeuroPoly Contributing Guidelines (DokuWiki) for [Issue labeling](https://www.neuro.polymtl.ca/open_source/contributing#issue_labels) and [PR labeling](https://www.neuro.polymtl.ca/open_source/contributing#pr_labels).
* I've modified `contributing.rst` to point to relevant contributing pages (GitHub repo, DokuWiki, GitHub wiki) instead of containing its own information.

If this sounds good, then the [ivadomed labels](https://github.com/ivadomed/ivadomed/labels) may need to be tweaked to match the format described in the DokuWiki. The [ivadomed Developer Wiki](https://github.com/ivadomed/ivadomed/wiki) may also need to be updated to document ivadomed-specific dev processes from `contributing.rst`.

(Cross-project coordination is tricky, though, so please feel free to share any thoughts you may have. :tada:)

### CODE REVIEW

**Review by jcohenadad — APPROVED** [review]
Thank you so much @joshuacwnewton !!!

I've slightly edited the [neuropoly wiki](https://www.neuro.polymtl.ca/open_source/contributing#pr_labels) to redirect to the changelog, so people have a bit more context

**Comment by joshuacwnewton** [comment]
Thanks for the approval, @jcohenadad. :slightly_smiling_face: 

I am also curious about input from @charleygros, @andreanne-lemay, and @lrouhier just to make sure the changes are OK with ivadomed's core team. (I wouldn't want to impose changes that weren't welcome! :sweat_smile:)

**Comment by andreanne-lemay** [comment]
Yes, this looks good :) and avoids duplication between ivadomed guidelines and neuropoly guidelines that are essentially the same! Thanks @joshuacwnewton

**Comment by charleygros** [comment]
(sorry for late reply, catching up with emails eheh)

Yeah Nah that's a beauty! Love it, will make the things so much easier! Thanks heaps @joshuacwnewton

**Pull request merged**
