### PR TITLE
Release v2.8.0 

### PR DESCRIPTION
**Pull request by dyt811**
Added 2.8.0 PR summary from Changelog-Neuropoly and updated version.txt

### CODE REVIEW

**Review by mariehbourget — COMMENTED** [review]
Thank you @dyt811 for taking care of this.
I have a question though regarding the changelog, it is normal that PRs from labels like "feature" or "installation" are not included?

**Comment by jcohenadad** [comment]
> I rolled back 2.8.0 release milestone until we get this resolved so the changelog would be more inclusive (we have been missing tons of stuff from prior release in release note I believe).

is that a problem if the tag is still present? (can it be deleted as well in the git history?):

image

**Comment by dyt811** [comment]
> is that a problem if the tag is still present? (can it be deleted as well in the git history?):

Yes, apparently it can. I just deleted the tag and last remnant of the troubled release has been erased for now.

**Comment by dyt811** [comment]
Alright. I used a locally patched version of `changelog` to generate these updated change logs and I think they are a lot more comprehensive than before.

**Review by mariehbourget — APPROVED** [review]
LGTM! Thank you @dyt811!

**Pull request merged**
