### PR TITLE
add conda environment and documentation for GPU support

### PR DESCRIPTION
**Pull request by taowa**
#### GitHub

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [ ] I've linked relevant issues in the PR body
- [x] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [x] I've assigned a reviewer

#### PR contents

- [x] I've consulted [ivadomed's internal developer documentation](https://github.com/ivadomed/ivadomed/wiki) to ensure my contribution is in line with any relevant design decisions
- [ ] (n/a) I've added [relevant tests](https://github.com/ivadomed/ivadomed/wiki/tests) for my contribution
- [x] I've updated the [relevant documentation](https://github.com/ivadomed/ivadomed/wiki/documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description
A user that wishes to install ivadomed using conda will install a version that does not include GPU support. This updates the documentation to make GPU support more obvious to enable.

### CODE REVIEW

**Comment by kousu** [comment]
Is this related to and/or superseding #951?

**Comment by taowa** [comment]
Nick, 2021-09-22 17:21 -0400:
> Is this related to and/or superseding #951?

Related-ish, but entirely compatible :).

 - tr

**Comment by dyt811** [comment]
So I updated the conda venv name and created a conda virtual environment called `IvadoMedEnv1` with everything else intact from your branch. 

I am seeing a lot of CuDNN errors. 

```
======================================================================================================================================== short test summary info =========================================================================================================================================
FAILED testing/unit_tests/test_HeMIS.py::test_HeMIS[loader_parameters0] - RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
FAILED testing/functional_tests/test_automate_training.py::test_automate_training[subprocess] - assert False
FAILED testing/functional_tests/test_automate_training.py::test_automate_training_run_test[subprocess] - assert False
FAILED testing/functional_tests/test_convert_to_onnx.py::test_convert_to_onnx - RuntimeError: CUDA error: no kernel image is available for execution on the device
FAILED testing/functional_tests/test_download_data.py::test_download_data_no_dataset_specified - SystemExit: 0
FAILED testing/functional_tests/test_segment_volume.py::test_segment_volume_2d_NumpyToTensor_retrocompatibility - RuntimeError: CUDA error: no kernel image is available for execution on the device
FAILED testing/functional_tests/test_segment_volume.py::test_segment_volume_2d - RuntimeError: CUDA error: no kernel image is available for execution on the device
FAILED testing/functional_tests/test_segment_volume.py::test_segment_volume_2d_no_prepro_transform - RuntimeError: CUDA error: no kernel image is available for execution on the device
FAILED testing/functional_tests/test_segment_volume.py::test_segment_volume_2d_with_patches[center_crop0] - RuntimeError: CUDA error: no kernel image is available for execution on the device
FAILED testing/functional_tests/test_segment_volume.py::test_segment_volume_3d[center_crop0] - RuntimeError: no valid convolution algorithms available in CuDNN
FAILED testing/unit_tests/test_testing.py::test_inference[testing_params0-roi_params0-target_lst0-test_lst0-transforms_dict0] - RuntimeError: CUDA error: no kernel image is available for execution on the device
FAILED testing/unit_tests/test_testing.py::test_inference[testing_params0-roi_params0-target_lst1-test_lst0-transforms_dict0] - RuntimeError: CUDA error: no kernel image is available for execution on the device
FAILED testing/unit_tests/test_testing.py::test_inference_2d_microscopy[testing_params0-roi_params0-target_lst0-test_lst0-transforms_dict0] - RuntimeError: CUDA error: no kernel image is available for execution on the device
FAILED testing/unit_tests/test_training_time.py::test_unet_time[train_lst0-config0-target_lst0] - RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
FAILED testing/unit_tests/test_training_time.py::test_unet_time[train_lst1-config1-target_lst0] - RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
FAILED testing/unit_tests/test_training_time.py::test_unet_time[train_lst2-config2-target_lst0] - RuntimeError: no valid convolution algorithms available in CuDNN
FAILED testing/unit_tests/test_training_time.py::test_unet_time[train_lst3-config3-target_lst0] - RuntimeError: no valid convolution algorithms available in CuDNN
FAILED testing/unit_tests/test_training_time.py::test_unet_time[train_lst4-config4-target_lst0] - RuntimeError: no valid convolution algorithms available in CuDNN
FAILED testing/unit_tests/test_training_time.py::test_unet_time[train_lst5-config5-target_lst0] - RuntimeError: no valid convolution algorithms available in CuDNN
======================================================================================================================== 19 failed, 184 passed, 945 warnings in 609.81s (0:10:09) ========================================================================================================================
```

Oddly, the pip list suggests CUDA 9.2 was installed. NO CLUE where that came from. Keep in mind that other conda env is working (or at least giving less errors). 

<details>

<summary>Pip list </summary>

```
(IvadoMedEnv1) dyt811@ArtemisIIUbuntu:~/git/ivadomed$ pip list
Package                           Version    Location
--------------------------------- ---------- -------------------------
absl-py                           0.14.0
alabaster                         0.7.12
attrs                             21.2.0
Babel                             2.9.1
backports.entry-points-selectable 1.1.0
bids-validator                    1.8.3
cachetools                        4.2.2
certifi                           2021.5.30
cfgv                              3.3.1
charset-normalizer                2.0.6
click                             8.0.1
coverage                          5.5
coveralls                         3.2.0
csv-diff                          1.1
cycler                            0.10.0
dictdiffer                        0.9.0
distlib                           0.3.3
docopt                            0.6.2
docutils                          0.17.1
filelock                          3.0.12
flake8                            3.9.2
future                            0.18.2
google-auth                       1.35.0
google-auth-oauthlib              0.4.6
grpcio                            1.40.0
h5py                              2.10.0
identify                          2.2.15
idna                              3.2
imageio                           2.9.0
imagesize                         1.2.0
iniconfig                         1.1.1
ivadomed                          2.8.0      /home/dyt811/git/ivadomed
Jinja2                            3.0.1
joblib                            1.0.1
jsonpointer                       2.1
kiwisolver                        1.3.2
loguru                            0.5.3
Markdown                          3.3.4
MarkupSafe                        2.0.1
matplotlib                        3.4.3
mccabe                            0.6.1
mock                              4.0.3
networkx                          2.6.3
nibabel                           3.2.1
nodeenv                           1.6.0
num2words                         0.5.10
numpy                             1.21.2
oauthlib                          3.1.1
onnxruntime                       1.4.0
packaging                         21.0
pandas                            1.3.3
patsy                             0.5.1
Pillow                            8.3.2
pip                               21.2.4
platformdirs                      2.3.0
pluggy                            1.0.0
pre-commit                        2.10.1
protobuf                          3.18.0
py                                1.10.0
pyasn1                            0.4.8
pyasn1-modules                    0.2.8
pybids                            0.13.2
pycodestyle                       2.7.0
pyflakes                          2.3.1
Pygments                          2.10.0
pypandoc                          1.6.4
pyparsing                         2.4.7
pytest                            6.2.5
pytest-console-scripts            1.2.0
pytest-cov                        2.12.1
pytest-ordering                   0.6
python-dateutil                   2.8.2
pytz                              2021.1
PyWavelets                        1.1.1
PyYAML                            5.4.1
requests                          2.26.0
requests-oauthlib                 1.3.0
rsa                               4.7.2
scikit-image                      0.18.3
scikit-learn                      0.24.2
scipy                             1.7.1
seaborn                           0.11.2
setuptools                        58.0.4
six                               1.16.0
snowballstemmer                   2.1.0
Sphinx                            4.2.0
sphinx-jsonschema                 1.16.11
sphinx-rtd-theme                  1.0.0
sphinxcontrib-applehelp           1.0.2
sphinxcontrib-devhelp             1.0.2
sphinxcontrib-htmlhelp            2.0.0
sphinxcontrib-jsmath              1.0.1
sphinxcontrib-qthelp              1.0.3
sphinxcontrib-serializinghtml     1.1.5
SQLAlchemy                        1.3.24
tensorboard                       2.6.0
tensorboard-data-server           0.6.1
tensorboard-plugin-wit            1.8.0
threadpoolctl                     2.2.0
tifffile                          2021.8.30
toml                              0.10.2
torch                             1.5.0+cu92
torchvision                       0.6.0+cu92
tqdm                              4.62.3
urllib3                           1.26.7
virtualenv                        20.8.0
Werkzeug                          2.0.1
wheel                             0.37.0
```
</details>

I vaguely recall it might be something related to how conda does not parse pip requirement file properly verbatim. 
Might have messed up this part somehow? I didn't test it too indepth. Before, I recall CPU version did not have these issue (probably also because it is not using CuDNN). Actually, I don't even think we tested CPU based conda even that much and it was already giving problem during earlier testing in https://github.com/ivadomed/ivadomed/pull/855 

```
# Torch GPU Version
--find-links https://download.pytorch.org/whl/torch_stable.html
torch==1.5.0
torchvision==0.6.0
```

Can we stand up a CI runner with GPU that we can test this against? it would be a lot easier (and more consistent) than manual dev/testing especially in case of consistency. If it is a Docker supported GPU runner that would be even better as that is apparently bleeding edge, if not even a GPU enabled shell runner works woonder. 

Worst come to worst, I suppose we can fork repo to GitLab, setup a private GPU shell runner somewhere on Rosenburg/Local/Romane or something and see.

**Comment by kousu** [comment]
> Oddly, the pip list suggests CUDA 9.2 was installed. NO CLUE where that came from. Keep in mind that other conda env is working (or at least giving less errors).

A guess: https://download.pytorch.org/whl/cu92/torch-1.5.0%2Bcu92-cp38-cp38-linux_x86_64.whl (and that cp36, cp37 variants) are last on the list on https://download.pytorch.org/whl/torch_stable.html. Perhaps, in the absence of being told explicitly with `+cu` version to use, it picked the last one it saw.

But why is that broken? Taowa didn't change the specs, just made the docs actually use them. When's the last time the GPU version was actually tested by anyone? @taowa, did you happen to run the tests or did you just test that this PR successfully installed?

**Comment by dyt811** [comment]
> But why is that broken? Taowa didn't change the specs, just made the docs actually use them. When's the last time the GPU version was actually tested by anyone? @taowa, did you happen to run the tests or did you just test that this PR successfully installed?

I suspect it is much more likely that we just do not have sufficient GPU based testing to begin with. i.e. before the PR, the GPU based testings were already buggy. Hence why if we can get some sort of GPU based auto (semi-automated even) testing on either Linux or Windows, it should help identify potential issues. 

Also ditto on CUDA11 pin if we have no other reason to stick with CUDA10. Drastically save testing debugging effort as well.

**Comment by dyt811** [comment]
Deprecated as we went with more consolidated simple assumption approach to avoid customizations, per PR#1129

**Pull request closed without merging**
