### PR TITLE
Registration pipeline

### PR DESCRIPTION
**Pull request by leandervaneekelen**
This is a pull request for the registration pipeline for the HeMIS dataset discussed in #471.

### CODE REVIEW

**Review by jcohenadad — CHANGES_REQUESTED** [review]
I would suggest to put these scripts in a project-specific repos, e.g. ivadomed/pipeline-hemis

**Comment by leandervaneekelen** [comment]
Good suggestion, will do.

**Comment by jcohenadad** [comment]
> Good suggestion, will do. Can you give me group permission to the ivadomed repositories so I can do that?

@alexfoias can you pls do that

**Comment by alexfoias** [comment]
@leandervaneekelen I created the repo https://github.com/ivadomed/pipeline-hemis and I gave you admin rights

**Pull request closed without merging**
