### PR TITLE
Add new custom css rule for table in purpose section (#617)

### LINKED ISSUE #617: Center cells in purpose
Here: https://ivadomed.org/en/latest/purpose.html#comparison-with-other-projects

It would be nice to have text in the cells centred (like the green checks / red cross).

### PR DESCRIPTION
**Pull request by gisellemartel**
## Description
Centered the text in the table for the "Purpose" section in the documentation

## Linked issues
Resolves: https://github.com/ivadomed/ivadomed/issues/617

### CODE REVIEW

**Comment by jcohenadad** [comment]
@gisellemartel the fields are still not centered (looking at the generated doc from https://github.com/ivadomed/ivadomed/pull/619/commits/25844f02b9569fbdde199b57fbf647c4b7c45f1b):
image

**Comment by gisellemartel** [comment]
@jcohenadad I generated the HTML file locally using sphinx and make as described here: https://github.com/ivadomed/ivadomed/wiki/documentation. The text is centered when I build the files on my machine. I am unable to to repro your issue. Were there any particular steps taken that were different from what was described in the wiki to generate the doc?
Screen Shot 2021-01-11 at 12 50 27 PM

**Comment by jcohenadad** [comment]
@gisellemartel the documentation is built with sphinx on the readthedocs server, we can look at the rendering of the documentation with your changes, and the "centering" does not show up:
https://ivado-medical-imaging--619.org.readthedocs.build/en/619/purpose.html

So something might need to be worked out in terms of how RTD builds the doc, etc.

**Comment by gisellemartel** [comment]
@jcohenadad great, thank you for the link! I think I have found the issue, appears to be a difference in the HTML elements that are rendered between sphinx and the RTD server. Will investigate a fix shortly

**Comment by jcohenadad** [comment]
you could find the link for all PRs here:
Screen Shot 2021-01-11 at 4 53 49 PM

**Comment by jcohenadad** [comment]
Awesome! it works well now. Unrelated, but I suggest to replace "Name" for "Feature" top/left column

**Comment by gisellemartel** [comment]
@jcohenadad do you propose I include the suggested change with this PR or would you prefer I open a new issue for this?

**Comment by jcohenadad** [comment]
> @jcohenadad do you propose I include the suggested change with this PR or would you prefer I open a new issue for this?

it's a small change, let's do it here

**Review by ahill187 — APPROVED** [review]
Looks good to me!

**Review by jcohenadad — APPROVED** [review]
Thank you for your contribution @gisellemartel !

**Pull request merged**
