### PR TITLE
Extract class SliceFilter, BalancedSample and SampleMetaData from loa…

### PR DESCRIPTION
**Pull request by konantian**
#### GitHub

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [ ] I've linked relevant issues in the PR body
- [x] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [x] I've assigned a reviewer

#### PR contents

- [x] I've consulted [ivadomed's internal developer documentation](https://github.com/ivadomed/ivadomed/wiki) to ensure my contribution is in line with any relevant design decisions
- [ ] I've added [relevant tests](https://github.com/ivadomed/ivadomed/wiki/tests) for my contribution
- [x] I've updated the [relevant documentation](https://github.com/ivadomed/ivadomed/wiki/documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description

* This PR extract the `SampleMetadata`, `BalancedSampler` and `SliceFilter` class outside of `loader/utils.py`. 

* This PR also updated all locations that referenced this class. 

* Refactor was carried out using PyCharm refactoring process. 

* No new features or bug fixes were introduced. Pure refactoring.

### CODE REVIEW

**Review by dyt811 — APPROVED** [review]
Thanks for taking care of this refactoring. 👍

**Comment by jcohenadad** [comment]
thank you for this refactoring-- however:
- in the future, could you please indicate the context/motivation for the refactoring (why was this done? relation to any issue? etc.)
- also, this was checked:
image

but i don't find these new files/classes on the API ref of the RTD

**Comment by konantian** [comment]
> thank you for this refactoring-- however:
> 
> * in the future, could you please indicate the context/motivation for the refactoring (why was this done? relation to any issue? etc.)
> * also, this was checked:
>   image
> 
> but i don't find these new files/classes on the API ref of the RTD

Thank you for your advice. I will make sure to indicate the motivation for future works. I think I miss checked that "relevant documentation" option and I will be more careful in the future.

**Comment by dyt811** [comment]
> thank you for this refactoring-- however:
> 
> * in the future, could you please indicate the context/motivation for the refactoring (why was this done? relation to any issue? etc.)

Hey, Julien. Good point. I assigned Yuan the ticket via our internal YouTrack ticket system so couldn't link it here but it was based on a project card created for it beforehand. I had added link the project ticket that were created for this and the other refactoring PR: https://github.com/ivadomed/ivadomed/projects/5#card-67261906.  Now moved to done. 

> * also, this was checked:
>   image
> 
> but i don't find these new files/classes on the API ref of the RTD

That is a good point. I checked it because I thought since this was a pure refactoring update (no functionalities added or removed), classes were just wholesale moved out into its own module for clarification. Hence, no documentation were updated as no functionalities were added/removed. I will keep in mind not to check those boxes but I didn't know there are a N/A category. These PR is designed to make future PR much easier to review than a massive `util.py` update containing 4+ classes and a dozen functions.

**Pull request merged**
