### PR TITLE
Automate_training: fix bug for multiple parameters

### PR DESCRIPTION
**Pull request by andreanne-lemay**
There was an issue with lists of parameters nested under the same dict key.
```
Example of hyperparameter:
{
  "training_parameters": {
    "batch_size": [2, 4, 8],
    "loss": [
      {"name": "DiceLoss"},
      {"name": "FocalLoss", "params": {"gamma": 0.5, "alpha" : 0.2}},
      {"name": "FocalLoss", "params": {"gamma": 0.2, "alpha" : 0.5}}
    ]
  },
  "default_model": {"depth": [2, 3, 4]}
}
```
Since ` batch_size` and `loss` are under `training_parameters` the flag -m doesn't work properly for this case. To fix this, a special case of `make_category` was added.

### CODE REVIEW

**Review by charleygros — APPROVED** [review]
Looks all good

My only hesitation is: WOuld it work if the first key is not a dict but a list parameters, eg:
```
    "gpu": [0, 1, 2],
```
PS: I know this example is silly eheh

Have you tried it yet? otherwise I am happy to give it a shot

**Comment by andreanne-lemay** [comment]
> Looks all good
> 
> My only hesitation is: WOuld it work if the first key is not a dict but a list parameters, eg:
> 
> ```
>     "gpu": [0, 1, 2],
> ```
> 
> PS: I know this example is silly eheh
> 
> Have you tried it yet? otherwise I am happy to give it a shot

No it doesn't work, but it never did. [This line](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/scripts/automate_training.py#L186) only works on dictionaries (because of the `.keys()`) . Since it doesn't concern the code introduced in this PR, I think we should fix this in a future PR. The only parameters that are not dicts are: gpu, command, log_directory, model_name, and debugging. I don't think this is a pressing matter since they are pretty much all irrelevant when it comes to do hyperparametrization, but it is good to keep this in mind! I'll open an issue.

**Comment by charleygros** [comment]
> No it doesn't work, but it never did. [This line](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/scripts/automate_training.py#L186) only works on dictionaries (because of the `.keys()`) . Since it doesn't concern the code introduced in this PR, I think we should fix this in a future PR. The only parameters that are not dicts are: gpu, command, log_directory, model_name, and debugging. I don't think this is a pressing matter since they are pretty much all irrelevant when it comes to do hyperparametrization, but it is good to keep this in mind! I'll open an issue.

I agree with all of these. Just wanted to kindly raise it :-)

**Comment by andreanne-lemay** [comment]
> > No it doesn't work, but it never did. [This line](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/scripts/automate_training.py#L186) only works on dictionaries (because of the `.keys()`) . Since it doesn't concern the code introduced in this PR, I think we should fix this in a future PR. The only parameters that are not dicts are: gpu, command, log_directory, model_name, and debugging. I don't think this is a pressing matter since they are pretty much all irrelevant when it comes to do hyperparametrization, but it is good to keep this in mind! I'll open an issue.
> 
> I agree with all of these. Just wanted to kindly raise it :-)

Opened here #587

**Pull request merged**
