### PR TITLE
Tutorial dataset: extraction from SpineGeneric

### LINKED ISSUE #253: Add link to (small) toy dataset for tutorial
Currently, the tutorial points to a 8GB dataset, which is too big. It would be nicer to point to a smaller data for our tutorials.

### LINKED ISSUE #288: Small dataset for tutorials
### Aim
Get a small dataset that we could use for tutorials, including training, inference, performance evaluation etc.

### Issues
A dataset that could be used to cover all the main features of the repo'.

### Suggestion:
- Source in SpineGeneric dataset: multi center, open source, SC segmentation and Disk levels already generated
    - Inconvenient: very large dataset. Solution: remove diffusion data + one subject per center
- Multi contrast --> demonstrate FiLM, MultiLabel segmentation, HeMIS
    - Inconvenient: different size. Potential Solution: use data after registration on the MT data.
        - Inconvenient of the potential solution: by doing so, we lose the brain area or sagittal view for disc detection. Potential solution BIS: one small dataset with multi-contrast data (all contrasts reg on MT) + one small dataset with T2 only: `multi_contrast_dataset` and `mono_contrast_dataset`.

### Features to illustrate
Here below the list of features we would like to illustrate. I "ticked" the features that could be illustrated with the above suggestion, if not: I tried to suggest a potential avenue to make it happen.

- [x] FiLMedUnet
- [x] HeMIS
- [x] Adaptative loader
- [x] 2D models
- [x] 3D models
- [x] Mono channel
- [x] Multi channel
- [ ] Multi target: only SC segmentation for now. Potential Avenue: + CSF? +GM on T2star?
- [x] BIDS
- [x] Transfer learning
- [x] Cascade approach
- [x] Segmentation
- [x] BoundingBox Localisation
- [ ] Slice-wise classification. Potential Avenue: Train a model to classify: slice with SC vs slice without SC on T1 or T2 data that include brain area, easily done with the SC mask we have.
- [x] Object detection, eg discs or PMJ
- [x] Training scheme: eg tune Loss, Learning Rate scheduler, transformations etc.
- [x] Evaluation scheme: choice of metrics, uncertainty

### PR DESCRIPTION
**Pull request by charleygros**
### Aim:
This PR introduces a small utility script, `dev/prepare_data/extract_small_dataset.py` which randomly extract a small BIDS dataset from a larger BIDS dataset.

### Script description:
```python
    """Extract small BIDS dataset from a larger BIDS dataset.

    Args:
        ifolder (string): Input BIDS folder.
        ofolder (string): Output folder.
        n (int): Number of subjects in the output folder.
        contrast_list (list): List of image contrasts to include. If set to None, then all available contrasts are
            included.
        include_derivatives (bool): If True, derivatives/labels/ content is also copied, only the raw images otherwise.
        seed (int): Set np.random.RandomState to ensure reproducibility: the same subjects will be selected if the
            function is run several times on the same dataset. If set to -1, each function run is independent.

    Returns:
        None
    """
```

Fixes #253, Fixes #288.

### CODE REVIEW

**Comment by charleygros** [comment]
Using this script, I created 2 small datasets that could be used for tutorials.

### Multicontrast non processed dataset
```
python extract_small_dataset.py -i duke/sct_testing/bids/spineGeneric_multiSubjects -n 10 -o small_nonprocessed_dataset -c T1w,T2w -d 0 -s 1234
```

- Output folder moved to: `duke/projects/ivadomed/tutorial_datasets`.
- 10 subjects
- No derivatives folder (not available)
- T1w, T2w

### Multicontrast processed dataset
```
python extract_small_dataset.py -i duke/projects/ivadomed/spineGeneric_201907041011 -n 10 -o small_processed_dataset -c T1w,T2w,T2star -d 1 -s 5678
```

- Output folder moved to: `duke/projects/ivadomed/tutorial_datasets`.
- 10 subjects
- Derivatives folder with `_seg-manual.nii.gz`
- T1w, T2w, T2star: registered on the MT data (high axial res)

**Comment by jcohenadad** [comment]
600MB seems excessive, i would expect no more than 20MB/subject for T1w, T2w, T2star. Maybe the GE sites have interpolated data, so we might want to exclude these sites.

**Comment by charleygros** [comment]
> 600MB seems excessive, i would expect no more than 20MB/subject for T1w, T2w, T2star. Maybe the GE sites have interpolated data, so we might want to exclude these sites.

My bad, it is actually 425MB in total, see `duke/projects/ivadomed/tutorial_datasets/small_processed_dataset`.
```
chgroc@rosenberg:~/duke/projects/ivadomed/tutorial_datasets$ du -h small_processed_dataset/
48K	small_processed_dataset/derivatives/labels/sub-cardiff03/anat
48K	small_processed_dataset/derivatives/labels/sub-cardiff03
41K	small_processed_dataset/derivatives/labels/sub-hamburg01/anat
41K	small_processed_dataset/derivatives/labels/sub-hamburg01
44K	small_processed_dataset/derivatives/labels/sub-juntendo750w01/anat
44K	small_processed_dataset/derivatives/labels/sub-juntendo750w01
48K	small_processed_dataset/derivatives/labels/sub-mpicbs06/anat
48K	small_processed_dataset/derivatives/labels/sub-mpicbs06
56K	small_processed_dataset/derivatives/labels/sub-oxfordFmrib07/anat
56K	small_processed_dataset/derivatives/labels/sub-oxfordFmrib07
56K	small_processed_dataset/derivatives/labels/sub-oxfordFmrib11/anat
56K	small_processed_dataset/derivatives/labels/sub-oxfordFmrib11
56K	small_processed_dataset/derivatives/labels/sub-sapienza05/anat
56K	small_processed_dataset/derivatives/labels/sub-sapienza05
48K	small_processed_dataset/derivatives/labels/sub-strasbourg04/anat
48K	small_processed_dataset/derivatives/labels/sub-strasbourg04
48K	small_processed_dataset/derivatives/labels/sub-tokyoSkyra06/anat
48K	small_processed_dataset/derivatives/labels/sub-tokyoSkyra06
56K	small_processed_dataset/derivatives/labels/sub-unf01/anat
56K	small_processed_dataset/derivatives/labels/sub-unf01
501K	small_processed_dataset/derivatives/labels
501K	small_processed_dataset/derivatives
45M	small_processed_dataset/sub-cardiff03/anat
45M	small_processed_dataset/sub-cardiff03
25M	small_processed_dataset/sub-hamburg01/anat
25M	small_processed_dataset/sub-hamburg01
36M	small_processed_dataset/sub-juntendo750w01/anat
36M	small_processed_dataset/sub-juntendo750w01
48M	small_processed_dataset/sub-mpicbs06/anat
48M	small_processed_dataset/sub-mpicbs06
47M	small_processed_dataset/sub-oxfordFmrib07/anat
47M	small_processed_dataset/sub-oxfordFmrib07
48M	small_processed_dataset/sub-oxfordFmrib11/anat
48M	small_processed_dataset/sub-oxfordFmrib11
37M	small_processed_dataset/sub-sapienza05/anat
37M	small_processed_dataset/sub-sapienza05
46M	small_processed_dataset/sub-strasbourg04/anat
46M	small_processed_dataset/sub-strasbourg04
48M	small_processed_dataset/sub-tokyoSkyra06/anat
48M	small_processed_dataset/sub-tokyoSkyra06
48M	small_processed_dataset/sub-unf01/anat
48M	small_processed_dataset/sub-unf01
425M	small_processed_dataset/
```

**Comment by jcohenadad** [comment]
can you do an ls to see what's inside one of the anat/?

**Comment by charleygros** [comment]
```
chgroc@rosenberg:~/duke/projects/ivadomed/tutorial_datasets$ ls small_processed_dataset/sub-sapienza05/anat
sub-sapienza05_T1w.json    sub-sapienza05_T2star.json    sub-sapienza05_T2w.json
sub-sapienza05_T1w.nii.gz  sub-sapienza05_T2star.nii.gz  sub-sapienza05_T2w.nii.gz
```

**Comment by charleygros** [comment]
```
chgroc@rosenberg:~/duke/projects/ivadomed/tutorial_datasets$ ll small_processed_dataset/sub-sapienza05/anat
total 37620
drwxr-xr-x 2 chgroc domain users     4096 Sep  4  2019 ./
drwxr-xr-x 2 chgroc domain users        0 Sep  4  2019 ../
-rwxr-xr-x 1 chgroc domain users     1884 Jul  4  2019 sub-sapienza05_T1w.json*
-rwxr-xr-x 1 chgroc domain users 21737659 Jul  4  2019 sub-sapienza05_T1w.nii.gz*
-rwxr-xr-x 1 chgroc domain users     1923 Jul  4  2019 sub-sapienza05_T2star.json*
-rwxr-xr-x 1 chgroc domain users 11211139 Jul  4  2019 sub-sapienza05_T2star.nii.gz*
-rwxr-xr-x 1 chgroc domain users     1873 Jul  4  2019 sub-sapienza05_T2w.json*
-rwxr-xr-x 1 chgroc domain users  5549144 Jul  4  2019 sub-sapienza05_T2w.nii.gz*
```

**Comment by jcohenadad** [comment]
all good! but these files are excessively big-- i suspect encoding is 64bit, which is an overkill. I need to review the process_data script.

**Comment by charleygros** [comment]
Script moved to `ivadomed/scripts/` + added to RTD.

**Pull request merged**
