### PR TITLE
Merged participants.tsv file saving bug correction

### PR DESCRIPTION
**Pull request by mpompolas**
Bug fix

Also moved the saving of merged participants.tsv file from MAIN to /loader/utils.py - get_new_subject_split()

### CODE REVIEW

**Review by ahill187 — COMMENTED** [review]
I'm not super familiar with this workflow, if you move these lines out of main:

```
participants_df = imed_loader_utils.merge_bids_datasets(context['loader_parameters']['path_data'])	
participants_df.to_csv(os.path.join(path_output, "participants.tsv"))
```

will that affect the `segment` functionality?

**Review by jcohenadad — COMMENTED** [review]
@mpompolas can you pls follow [convention](https://www.neuro.polymtl.ca/software/contributing#pr_title) for PR titles (remove Kn/merged-- and give intuitive name)-- also add labels-- thanks!

**Comment by andreanne-lemay** [comment]
> I'm not super familiar with this workflow, if you move these lines out of main:
> 
> ```
> participants_df = imed_loader_utils.merge_bids_datasets(context['loader_parameters']['path_data'])	
> participants_df.to_csv(os.path.join(path_output, "participants.tsv"))
> ```
> 
> will that affect the `segment` functionality?

The new option to merge datasets does not work with the command `segment` #685, but you are right (nice catch!). When we use the command `segment`, the dataset is not split, so not merged if the code is removed from `main`.

**Comment by mpompolas** [comment]
> @mpompolas can you pls follow [convention](https://www.neuro.polymtl.ca/software/contributing#pr_title) for PR titles (remove Kn/merged-- and give intuitive name)-- also add labels-- thanks!

Will do.


Nice catch @ahill187 . Missed it on the previous merge, but as @andreanne-lemay mentioned the merged df is not used in segment. Taking care of this now

**Comment by mpompolas** [comment]
It's working now. Let me know so we can merge it.

The saving of the merged `participants.tsv` file stays in `/loader/utils.py - get_new_subject_split()` unless there is an objection to that

**Review by andreanne-lemay — APPROVED** [review]
I tested the `segment` command on my station and it works! The code looks good to me  :100:

**Comment by mpompolas** [comment]
thanks for checking everybody

**Pull request merged**
